// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('add_product', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('add_product', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect(1511, 859)
    await driver.findElement(By.linkText("Add Product")).click()
    await driver.findElement(By.id("title")).click()
    await driver.findElement(By.id("title")).sendKeys("The New Product")
    await driver.findElement(By.id("imageUrl")).click()
    await driver.findElement(By.id("imageUrl")).sendKeys("https://www.google.de/search?q=pictures&sxsrf=ALeKk02ewiAbIQm_olHh0_r6M_JHgFH5Vg:1616976175061&tbm=isch&source=iu&ictx=1&fir=5wpmfzF3T_j--M%252CNPxUjK-ZSJCGeM%252C_&vet=1&usg=AI4_-kTukNLrmTppTsTk4v4lHVomxsX4fw&sa=X&ved=2ahUKEwi34ZjUmdTvAhUPwKQKHZFXDlIQ9QF6BAgYEAE#imgrc=5wpmfzF3T_j--M")
    await driver.findElement(By.id("price")).click()
    await driver.findElement(By.id("price")).sendKeys("76.22")
    await driver.findElement(By.id("description")).click()
    await driver.findElement(By.id("description")).sendKeys("A new Product")
    await driver.findElement(By.css(".btn")).click()
   // await driver.findElement(By.css(".card:nth-child(5) form > .btn")).click()
   
  })
})

