// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('check_header', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('check_header', async function() {
    // Test name: check_header
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 1511x859 | 
    await driver.manage().window().setRect(1511, 859)
    // 3 | click | linkText=Shop | 
    await driver.findElement(By.linkText("Shop")).click()
    // 4 | click | linkText=Products | 
    await driver.findElement(By.linkText("Products")).click()
    // 5 | click | linkText=Cart | 
    await driver.findElement(By.linkText("Cart")).click()
    // 6 | click | linkText=Orders | 
    await driver.findElement(By.linkText("Orders")).click()
    // 7 | click | linkText=Add Product | 
    await driver.findElement(By.linkText("Add Product")).click()
    // 8 | click | linkText=Admin Products | 
    await driver.findElement(By.linkText("Admin Products")).click()
  })
})
